### ISSUE TITLE
Merges mappings even with noCompatMode: true

### ISSUE THREAD

**Issue by johanla0** [pascalre/vscode-yaml-sort#41]
I am using Merge Key Language-Independent Type for YAML™ Version 1.1 as described [here](https://yaml.org/type/merge.html) because it's more convenient to have some keys in one place. Still, the extension inserts all the mappings where they were used with << merge key even when noCompatMode: true is set.

Is the behavior expected?

**Comment by pascalre** [comment]
@johanla0 If the setting `noCompatMode` is set to `true` the formatter doesn't try to be compatible with older yaml versions, e. g. YAML 1.1. Since the merge key `<<` is no part of any YAML spec, it was not intended to be a feature of this formatter.
To solve your problem you could use YAML references, like
```
- reference: &ref_0
    - tag1
    - tag2
- key: *ref_0
```

If you still miss the support for merge keys in this extension, please feel free to contribute and PR.
